services:
  # Polling web app
  next_webapp:
    build:
      context: ./webapp
    container_name: next_webapp
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy

  # Postgres Database
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
