import type { Metadata } from "next";
import "./globals.css";
import { Roboto, Roboto_Slab, BBH_Bogle, Geist_Pixel } from "next/font/google";
import { cn } from "@/lib/utils";
import { NavAuth } from "@/components/nav-auth";
import Link from "next/link";

const bbhBogleHeading = BBH_Bogle({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-heading",
});

const roboto = Geist_Pixel({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full antialiased",
        "font-sans",
        roboto.variable,
        bbhBogleHeading.variable,
      )}
    >
      <body className="dark min-h-full flex flex-col bg-image-grid">
        <nav className="flex justify-between px-18 py-8 border-b border-primary/35">
          <Link
            className="font-heading text-2xl font-bold text-foreground"
            href="/"
          >
            Pollit
          </Link>
          <NavAuth />
        </nav>

        {children}
      </body>
    </html>
  );
}
