import type { Metadata } from "next";
import "./globals.css";
import { Roboto, Roboto_Slab } from "next/font/google";
import { cn } from "@/lib/utils";
import { NavAuth } from "@/components/nav-auth";
import Link from "next/link";

const robotoSlabHeading = Roboto_Slab({
  subsets: ["latin"],
  variable: "--font-heading",
});

const roboto = Roboto({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full antialiased",
        "font-sans",
        roboto.variable,
        robotoSlabHeading.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <nav className="bg-black text-white flex justify-between px-6 py-4 font-heading min-h-14">
          <Link href="/">Poll it!</Link>
          <NavAuth />
        </nav>

        {children}
      </body>
    </html>
  );
}
