name: Docker deploy to droplet

on:
    push:
        branches:
            - main
        tags:
            - "v*"
    pull_request:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: read
    packages: write

jobs:
  # Build and push image containers
    build-and-push:
        runs-on: ubuntu-latest
        outputs: 
          image_tag: ${{ steps.meta.outputs.version }}
        steps:
            - uses: actions/checkout@v6
            - name: Log in to the Container registry
              uses: docker/login-action@v4
              with: 
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4
            - name: Extract metadata for Docker
              id: meta
              uses: docker/metadata-action@v6
              with:
                images: ghcr.io/andresborn/polling-webapp
            - name: Build and push Docker images
              uses: docker/bake-action@v7
              env:
                IMAGE_TAG: ${{ steps.meta.outputs.version }}
              with:
                targets: next_webapp,migrate
                push: true
  # (Todo: Test)
  # SSH to droplet
    SSH-and-pull:
      needs: build-and-push
      runs-on: ubuntu-latest
      steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        env:
          IMAGE_TAG: ${{ needs.build-and-push.outputs.image_tag }}
        with:
          envs: IMAGE_TAG
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_KEY }}
          script: |
            set -e
            cd polling-webapp
            git pull
            sudo -E docker compose pull next_webapp db 
            sudo -E docker compose --profile tools pull migrate
            sudo -E docker compose up -d db
            sudo -E docker compose run --rm --no-build migrate
            sudo -E docker compose up -d --no-build

# Pull containers from registry

# Start containers